### ISSUE TITLE
'Export to markdown' on extracted annotations not working

### ISSUE THREAD

**Issue by DitDotz** [argenos/zotero-mdnotes#149]
**Describe the bug**
'Export to markdown'  on extracted annotations not working.

**To Reproduce**
1. Clicked 'Export to markdown' on extracted annotations

4. See error in debug output logging:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data noteToMarkdown@chrome://mdnotes/content/mdnotes.js:362:14 getZoteroNoteFileContents@chrome://mdnotes/content/mdnotes.js:733:14 exportToMarkdownMenu@chrome://mdnotes/content/mdnotes.js:1030:26

**Expected behavior**
To have extracted annotations converted to markdown file at specified location

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Zotero version: [5.0.96.3]
 - Mdnotes version: [0.1.3]
 - Zotfile version: [5.1.0]
 - BetterBibtex version: [6.1.10]

**Comment by MSBack** [comment]
I am experiencing the same bug using beta 6.0.9-beta.6+b215d93ac.

**Comment by Longyichen** [comment]
yes，same bug in zotero 6.0.23 + mdnotes 0.2.3

**Comment by Naturalifica** [comment]
exactly same problem

**Comment by hajdukste** [comment]
What error are you getting? In Zotero, you can enable debug logging by going to Help -> Debug Output Logging -> Enable and View Output, and then performing the export. I was encountering an error that Zotero.MarkdownUtils was not defined. This was because I had packaged the source code into an xpi file myself, which has mdnotes.js and markdown-utils.js in different folders.

If I use the original xpi file, I can export the annotations. When I examined how the xpi file was packaged by renaming it to zip, I noticed that these two files were actually in the same folder, so I think that is the reason for the error.

I am using Zotero 6.0.37 with mdnotes 0.2.3.
