### ISSUE TITLE
Seperated notes and integration notes

### ISSUE THREAD

**Issue by trungng2006** [argenos/zotero-mdnotes#17]
Would it be possible to export 2 types of file:
1. Notes and highlights are export separately (each note and highlights will have their own unique ID)
2. The integration file. This file will have the article metadata and it also embed all the notes and highlights (![[highlight unique ID]])
    So the integration file would look like this:
    https://ibb.co/hmMT14t

**Comment by argenos** [comment]
@trungng2006 I'm not sure that #35 fully solves what you want to do here. Could you test this out? 

I believe most of this would be accomplished if you use separate colors for annotations and highlights (so Zotfile extracts each of those into separate notes). The template would allow you to customize where to place the metadata and highlights. Using the custom formatting you could add the `!` in the `field_content` of the notes, i.e. modify it so that it looks as `field_content: !{{content}}`. Keep in mind that this means notes will *always* be transcluded.
