### ISSUE TITLE
citekey in metadata file

### ISSUE THREAD

**Issue by linxule** [argenos/zotero-mdnotes#2]
https://github.com/argenos/zotero-mdnotes/blob/de6701914e62ff189ecd8d9d8abfa75efc149343/content/mdnotes.js#L205

This currently gives output "`citekey`" rather than "citekey" or "@citekey"

**Comment by argenos** [comment]
This was a bit of a personal preference, as I tend to copy the cite key to use in LaTeX directly. I'm not opposed to removing the code block formatting, but when using pandoc having `@` in that field would render the citation instead of displaying the cite key (at least from what I gather), so I would opt for the former.

**Comment by argenos** [comment]
Fixed in ac44dcdb6a432ff60d8e9d29351cf65ba0567608
