### ISSUE TITLE
Allow extraction of year alone from {{date}} for items that have day and month in addition to year

### ISSUE THREAD

**Issue by Cateroo** [argenos/zotero-mdnotes#74]
This is a feature request; currently, articles, books, cases, etc that have a date+month+year are extracted as is from zotero into the markdown note without additional formatting. I tend to prefer tagging just the year for most of my references as more details clutter up connections in backlinking. This is particularly true for legal cases, where the year of judgement is usually relevant information for drawing up data on patterns of adjudication, but I still need to retain the decision month and date in zotero for citations. 

It would be great if extraction of just the year, or something that can format the date into specific day/month/year tags could be built for this.

**Comment by welpdx** [comment]
I can't even figure out where the {{date}} or {{dateCreated}} placeholder preference is located. I can't find it in the Config Editor nor in `%appdata%\Zotero\Zotero\Profiles\randomstrings.profilename\pref.js`

I doubt it is just from the default zotero field name because {{date}} in the template translates to `* Date: [[MMM DD, YYYY]]`
